// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASkIyAuBXnZjIcFIG8ehkmWd1uhyzF2KM',
    appId: '1:744559441199:web:4a318c41e6eb000e665dda',
    messagingSenderId: '744559441199',
    projectId: 'flutter-firebases4',
    authDomain: 'flutter-firebases4.firebaseapp.com',
    storageBucket: 'flutter-firebases4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA6gogGcZNR8U7tZXBWRMWit9hQDU16Ks',
    appId: '1:744559441199:android:2d57366388fbabdf665dda',
    messagingSenderId: '744559441199',
    projectId: 'flutter-firebases4',
    storageBucket: 'flutter-firebases4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ8bulh0GGCkJsQfd5xas6ci4wJDv_-tM',
    appId: '1:744559441199:ios:81819861ea3fef51665dda',
    messagingSenderId: '744559441199',
    projectId: 'flutter-firebases4',
    storageBucket: 'flutter-firebases4.appspot.com',
    iosBundleId: 'com.example.chatFirebaseS4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ8bulh0GGCkJsQfd5xas6ci4wJDv_-tM',
    appId: '1:744559441199:ios:d0f550b549b41695665dda',
    messagingSenderId: '744559441199',
    projectId: 'flutter-firebases4',
    storageBucket: 'flutter-firebases4.appspot.com',
    iosBundleId: 'com.example.chatFirebaseS4.RunnerTests',
  );
}
